services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Team23\T23InlineContainer\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Team23\T23InlineContainer\Tca\ItemProcFunc:
    public: true

  Team23\T23InlineContainer\Tca\AddFieldToAllContainers:
    tags:
      - name: event.listener
        identifier: 'addFieldToAllContainers'
        event: TYPO3\CMS\Core\Configuration\Event\AfterTcaCompilationEvent